version: "3.7"

services:
  demo_db:
    image: postgres
    volumes:
      - demo_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"

volumes:
  demo_db:
