# Generated by Django 3.1.7 on 2021-03-26 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('units', models.DecimalField(decimal_places=1, max_digits=18)),
                ('room', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('days', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.subject')),
            ],
        ),
    ]
