# Generated by Django 3.1.7 on 2021-03-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(through='enrollment.StudentSubject', to='enrollment.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(through='enrollment.StudentSubject', to='enrollment.Student'),
        ),
    ]
